<script lang="ts">
  import { page } from '$app/state';
  import type { BoardProject, BoardUser, UserRole } from '$lib/types';
  let { data, form }: { data: { superadmin: string; users: BoardUser[]; projects: BoardProject[]; settings: Record<string, string> }; form?: { message?: string; error?: string } } = $props();
  const roleOptions: Exclude<UserRole, 'superadmin'>[] = ['admin', 'editor', 'viewer'];
</script>

<svelte:head><title>Settings · Project Agile Board</title></svelte:head>
<main class="settings-shell">
  <header class="topbar"><div><p class="eyebrow">ADMINISTRATION</p><h1>System settings</h1><p class="subtitle">Manage access without editing deployment secrets.</p></div><a class="quiet-button settings-back" href="/">Back to board</a></header>
  <section class="settings-card"><p class="eyebrow">ROLES</p><h2>Access model</h2><p class="subtitle">The deployment credentials are always the <strong>superadmin</strong> bootstrap account. Database users can be administrators, editors, or viewers.</p><dl class="role-list"><dt>superadmin</dt><dd>Deployment owner; can manage every setting.</dd><dt>admin</dt><dd>Can create users, change roles, and remove users.</dd><dt>editor</dt><dd>Can work with board transitions and notes.</dd><dt>viewer</dt><dd>Read-only board access.</dd></dl></section>
  <section class="settings-card"><div class="settings-heading"><div><p class="eyebrow">PROJECTS</p><h2>Project ownership</h2></div><a class="quiet-button" href="/projects/new">New project</a></div><p class="subtitle">Projects are private by default. Start a new workspace from a focused template, then tune its workflow and invite access as it becomes ready.</p>{#if data.projects.length}<ul class="user-list">{#each data.projects as project}<li><div><strong>{project.name}</strong><span class="role">{project.visibility}</span></div><small>{project.slug} · owner: {project.owner}</small><a href={`/projects/${project.slug}/settings`}>Open project settings</a></li>{/each}</ul>{:else}<div class="empty-slate"><img src="/assets/illustrations/project-team.svg" alt="" /><div><strong>No projects yet</strong><p class="empty">Create the first workspace from a ready-made workflow.</p><a class="quiet-button" href="/projects/new">Choose a template</a></div></div>{/if}</section>
  <section class="settings-card"><p class="eyebrow">SYSTEM POLICY</p><h2>Admin controls</h2><p class="subtitle">These settings affect registration and automatic access for new accounts. Existing users are unchanged.</p><form method="POST" action="?/saveSettings" class="policy-form"><label class="check"><input type="checkbox" name="registrationEnabled" checked={data.settings.registration_enabled !== 'false'} /> Allow self-registration</label><label>New account role <select name="defaultRole"><option value="viewer" selected={data.settings.default_role !== 'editor'}>viewer</option><option value="editor" selected={data.settings.default_role === 'editor'}>editor</option></select></label><label>GitHub account role <select name="githubDefaultRole"><option value="viewer" selected={data.settings.github_default_role !== 'editor'}>viewer</option><option value="editor" selected={data.settings.github_default_role === 'editor'}>editor</option></select></label><label>Default project visibility <select name="visibility"><option value="private" selected={data.settings.project_visibility !== 'shared'}>private</option><option value="shared" selected={data.settings.project_visibility === 'shared'}>shared</option></select></label><button type="submit">Save admin settings</button></form></section>
  <section class="settings-card"><p class="eyebrow">APPEARANCE</p><h2>Visual customization</h2><p class="subtitle">Choose a comfortable baseline for everyone using this deployment.</p><form method="POST" action="?/saveSettings" class="policy-form"><label>Theme <select name="theme"><option value="midnight" selected={data.settings.theme !== 'ocean' && data.settings.theme !== 'light'}>Midnight</option><option value="ocean" selected={data.settings.theme === 'ocean'}>Ocean</option><option value="light" selected={data.settings.theme === 'light'}>Light</option></select></label><label>Accent color <select name="accent"><option value="#73b6ff" selected={data.settings.accent !== '#7de0aa' && data.settings.accent !== '#ffb86b'}>Sky blue</option><option value="#7de0aa" selected={data.settings.accent === '#7de0aa'}>Mint</option><option value="#ffb86b" selected={data.settings.accent === '#ffb86b'}>Amber</option></select></label><label>Default card density <select name="density"><option value="comfortable" selected={data.settings.density !== 'compact'}>Comfortable</option><option value="compact" selected={data.settings.density === 'compact'}>Compact</option></select></label><button type="submit">Save appearance</button></form></section>
  <section class="settings-card"><div class="settings-heading"><div><p class="eyebrow">USERS</p><h2>Team access</h2></div><span class="health valid">{data.users.length + 1} accounts</span></div>{#if form?.message}<p class="success" role="status">{form.message}</p>{/if}{#if form?.error}<p class="action-errors" role="alert">{form.error}</p>{/if}<ul class="user-list"><li><div><strong>{data.superadmin}</strong><span class="role role-superadmin">superadmin</span></div><small>Deployment credential · cannot be removed here</small></li>{#each data.users as user}<li><div><strong>{user.username}</strong><span class={`role role-${user.role}`}>{user.role}</span></div><small>Added {new Date(user.createdAt).toLocaleDateString()}</small><div class="user-actions"><form method="POST" action="?/updateRole"><input type="hidden" name="username" value={user.username} /><select name="role" aria-label={`Role for ${user.username}`}>{#each roleOptions as role}<option value={role} selected={role === user.role}>{role}</option>{/each}</select><button type="submit" class="quiet-button">Save role</button></form><form method="POST" action="?/deleteUser"><input type="hidden" name="username" value={user.username} /><button type="submit" class="quiet-button danger">Remove</button></form></div></li>{/each}</ul></section>
  <section class="settings-card"><p class="eyebrow">ADD ACCOUNT</p><h2>Invite a user</h2><form method="POST" action="?/createUser" class="user-form"><label>Username <input name="username" autocomplete="off" required minlength="3" maxlength="48" /></label><label>Temporary password <input name="password" type="password" autocomplete="new-password" required minlength="8" /></label><label>Role <select name="role"><option value="viewer">viewer</option><option value="editor">editor</option><option value="admin">admin</option></select></label><button type="submit">Create account</button></form></section>
</main>
